name: Lint, Pack, Publish

on: [push, pull_request]

jobs:
  lint-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install CI Utilities
      run: |
        pip install pip-tools==7.*
        pip-compile --extra dev -o - pyproject.toml | pip install -r /dev/stdin -U

    - name: Lint
      run: |
        black --check .
        ruff check .

    - name: Package
      run: |
        python -m build
        twine check dist/*

    - name: Upload Package Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: Package Artifacts
            path: dist/
            if-no-files-found: error
